global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

#  Postgres Exporter for one postgres instance
  # - job_name: 'postgres_exporter'
  #   static_configs:
  #     - targets: ['postgres_exporter:9187']

# multitarget setup
  - job_name: 'postgres'
    static_configs:
      - targets:
        - postgres-1:5432
        - postgres-2:5432
    metrics_path: /probe
    params:
      auth_module: [localhost]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres_exporter:9187  # The postgres exporter's real hostname:port.
